### ISSUE TITLE
Version & Tag

### ISSUE THREAD

**Issue by DerStoffel** [MewesK/TwigExcelBundle#1]
Would you mind tagging your 1.1 version?

I am about to migrate from liuggio/excelbundle which depends on phpoffice/phpexcel: 1.8.0.

So if I want to use your bundle I'd have to replace all, or deal with the conflict in versions.
Since your dev-master does not present this issue anymore due to the newer phpexcel version,
I'd love for you to tag it.

Cheers

**Comment by MewesK** [comment]
Will be done in the next 24h. And thanks for the tweet :)

**Comment by plfort** [comment]
+1
