### ISSUE TITLE
Merge cells/rows

### ISSUE THREAD

**Issue by malheirosrafa** [MewesK/TwigExcelBundle#10]
I cannot find a way to merge cells/rows, some method already exists? 
If not, have some tips from how to create this in a fork?

Thanks!

**Comment by malheirosrafa** [comment]
I made it and submited a pull request, works like this:
`{% xlscell { merge:'C' } %} cell content {% endxlscell %}`

**Comment by hossam-maurice-zz** [comment]
I am unable to merge cells using variable or array length like in the example below:
`{% xlscell { merge: array|length } %} cell content {% endxlscell %}`

So what is the correct syntax for this case?

Please note that when I  put the variable between brackets my computer **freezes**, as follows:
`{% xlscell { merge: (array|length) } %} cell content {% endxlscell %}`

Thank you in advance
