### ISSUE TITLE
Leading zeros problem in a string that contains an integer

### ISSUE THREAD

**Issue by aserratorta** [MewesK/TwigExcelBundle#16]
I have a problem when I try to render a string that contains an integer value into  a cell.

```
{% xlscell { dataType: 's' }%}
       {{ myValue }}
{% endxlscell %}
```

If myValue = '1.50' (as a string) then it renders a 1.5 integer value into excel file. I found some information [here](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/07-Accessing-Cells.md#setting-a-number-with-leading-zeroes) and [here](https://github.com/PHPOffice/PHPExcel/issues/493)

The problem is that I need to execute setValueExplicit method instead of setValue.

I can provide a PR to solve this behaviour if you want. Are you agree?

**Comment by davidromani** [comment]
👍

**Comment by MewesK** [comment]
Thanks for the PR! I have renamed the property to 'explicitValue' to fit the naming scheme better and  added a unit test to cover the new feature. Will be part of version 2.2 which will be released today.

**Comment by aserratorta** [comment]
You’re welcome!
