### ISSUE TITLE
How to save generated file in server?

### ISSUE THREAD

**Issue by sdkcarlos** [MewesK/TwigExcelBundle#22]
With the providen examples, you can generate an excel file to serve as download for the user, however is there a way to save the generated file in the server?

**Comment by MewesK** [comment]
Just use the $this->render method within the controller to get the raw binary data and save it to disk. (https://symfony.com/doc/current/quick_tour/the_view.html) Since you're using Symfony anyways you could use the Filesystem component to do that. (http://symfony.com/doc/current/components/filesystem.html#dumpfile)

Hope that helps!

**Comment by sdkcarlos** [comment]
I'm getting the following exception while saving the `$this->render` to a variable (accessing www.domain.com/generate-excel), my controller:

```php
<?php

namespace sandbox\mainBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

class DefaultController extends Controller
{
    public function indexAction(Request $request)
    {
        // Throws exception ...
        $binaryExcelContent = $this->render('sandboxmainBundle:Default:example.xlsx.twig', [
            'data' => ['La', 'Le', 'Lu']
        ]);

        // Never thrown ...
        return new Response("It works ?");
    }
}
```

and the TwigView (`template.xlsx.twig`) very simple, taken from the docs :

```twig
{% xlsdocument %}
    {% xlssheet 'Worksheet' %}
        {% xlsrow %}
            {% xlscell { style: { font: { size: '18' } } } %}Values{% endxlscell %}
        {% endxlsrow %}
        {% for value in data %}
            {% xlsrow %}
                {% xlscell %}{{ value }}{% endxlscell %}
            {% endxlsrow %}
        {% endfor %}
    {% endxlssheet %}
{% endxlsdocument %}
```

The exception is:

>  InvalidArgumentException: Unknown format "html" in vendor\mewesk\twig-excel-bundle\Wrapper\XlsDocumentWrapper.php at line 205 

This exception is thrown in the controller, however , if i set the name of the route to : www.mydomain.com/generate-excel.xlsx (providing a format in the URL) then the error will be thrown by twig:

> Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("Unknown format "html"") in myBundle:Default:template.xlsx.twig at line 1.

The error seems to be someway related in the [XlsDocumentWrapper.php](https://github.com/MewesK/TwigExcelBundle/blob/master/Wrapper/XlsDocumentWrapper.php#L205) while trying to get the format, is there a way in which i can specify the format dinamically from the controller?
