### ISSUE TITLE
Add template in xlsdocument

### ISSUE THREAD

**Issue by roberlan** [MewesK/TwigExcelBundle#23]
I can' t add the documentation template to my bundle. I have tried with the address and the notation. Please could you help me.
`{% xlsdocument {'template': './template_advanced.xlsx'} %}
      {% xlssheet %}
        {% xlsrow %}
            {% xlscell %}Hello2{% endxlscell %}
        {% endxlsrow %}
        {% xlsrow %}
            {% xlscell 1 %}Bar2{% endxlscell %}
        {% endxlsrow %}
      {% endxlssheet %}
    {% endxlsdocument %}`

**Comment by MewesK** [comment]
`{% xlsdocument { 'template': '@App/template_advanced.xlsx' } %}` should work if `template_advanced.xslx` is in `src/AppBundle/Resources/views`. It's part of the unit tests.
