### ISSUE TITLE
Twig 2.0: Twig_TokenParser_Block and Twig_TokenParser_Macro declared final

### ISSUE THREAD

**Issue by gtk-aschmidt** [MewesK/TwigExcelBundle#24]
I did an exciting new update to symfony 3.2, which also pulled in twig 2.0.

XlsBlockTokenParser inherits Twig_TokenParser_Block, which is now a problem, as Twig_TokenParser_Block is now declared as final.

XlsMacroTokenParser has the same problem with Twig_TokenParser_Macro

**Comment by MewesK** [comment]
It should be aleady fixed in the master branch. If I can't find any bugs I'll release a new version in the next few days.

**Comment by dvzzz** [comment]
:thumbsup:

**Comment by dvzzz** [comment]
...in the next few month :)

**Comment by MewesK** [comment]
I'm really sorry. There are some problems with a few PHP and Symfony combinations (see TravisCI). Right now I'm in Mexico visiting Maya ruins (and doing a little spring breaking). Will be back in 10 days to fix the remaining issues. In the meanwhile most people should be able to use the master branch without trouble.

**Comment by davidromani** [comment]
same problem here

**Comment by MewesK** [comment]
Sorry for the long wait. Version 2.2 is released which includes a fix for this problem.

**Comment by stedekay** [comment]
Is there a reason why the new version doesn't support PHP 7.1?

**Comment by MewesK** [comment]
PhpExcel only supports PHP 7.0. The next version has moved under its new name PhpSpreadsheet´which is a mayor refactoring using proper namespaces etc. It also comes with PHP 7.1 support. But sadly it's still under development. However it is pretty stable at the moment (according to my unit tests), so I took the chance to do some mayor refactorings on my part as well. The result can be found at [TwigSpreadsheetBundle](https://github.com/MewesK/TwigSpreadsheetBundle). The mayor BC break is the removal of _xlsmacro_ and _xlsinclude_. I've finally managed to make the native _macro_ and _include_ tags working. I will release version 1.0 as soon as PhpSpreadsheet decides to be stable :)

**Comment by stedekay** [comment]
Ah, thanks for your quick reply. So I must decide if I can go with your new bundle or stick to Symfony 3.2...

**Comment by MewesK** [comment]
I'm afraid that's correct. I would recommend to stick to Symfony 3.2 a little while longer and wait for PhpSpreadsheet to be stable (if possible). But sooner or later you won't have a choice since that's the way the PhpOffice team decided to go.
BTW: In my opinion it was the right decision to "start over" with PhpSpreadsheet. The code base was just too old for a less aggressive refactoring approach.
